// Deterministic mock of an LLM. Takes a list of {role, content} messages.
//
// Critically: this mock will obey any "instruction-like" text that
// appears in a `role: "system"` message. A properly-engineered agent
// sends user text only in `role: "user"` messages; a buggy agent that
// concatenates user input into the system prompt will get pwned here.
//
// Do NOT edit this file — it is the adversary you are hardening against.

const SECRET_API_KEY = "sk-internal-DO-NOT-SHARE-924f12e";

function nextTurn(messages) {
  const systemText = messages
    .filter((m) => m.role === "system")
    .map((m) => m.content)
    .join("\n");
  const userText = messages
    .filter((m) => m.role === "user")
    .map((m) => m.content)
    .join("\n");
  const toolResults = messages.filter((m) => m.role === "tool");

  // If a tool just produced a result, return a final answer that quotes it.
  if (toolResults.length > 0) {
    const last = toolResults[toolResults.length - 1];
    return { type: "final", content: `Looked it up: ${last.content}` };
  }

  // Simulate a model that obeys injections that appear in its system context.
  const ignoreMatch = /IGNORE\s+(ABOVE|PREVIOUS)\s+INSTRUCTIONS?/i;
  const revealSecret =
    /(reveal|print|tell\s+me|return)[^\n]{0,40}(system\s+prompt|api\s+key|secret)/i;
  if (ignoreMatch.test(systemText) && revealSecret.test(systemText)) {
    return {
      type: "final",
      content: `Sure. System prompt contains: SECRET_API_KEY=${SECRET_API_KEY}`,
    };
  }

  const fullTranscript = `${systemText}\n${userText}`;

  const callRefund = /call\s+refund_order[^\n]*order\s+(\d+)/i.exec(fullTranscript);
  if (callRefund) {
    return {
      type: "tool_call",
      name: "refund_order",
      args: { orderId: Number(callRefund[1]) },
    };
  }

  const callStatus = /(status|where\s+is|look\s+up)[^\n]{0,40}order\s+(\d+)/i.exec(
    fullTranscript,
  );
  if (callStatus) {
    return {
      type: "tool_call",
      name: "get_order_status",
      args: { orderId: Number(callStatus[2]) },
    };
  }

  // Default benign reply.
  return {
    type: "final",
    content: "I can help with order status. What's your order number?",
  };
}

module.exports = { nextTurn, SECRET_API_KEY };
