import Link from "next/link";

export default function LandingPage() {
  return (
    <main className="mx-auto flex min-h-screen max-w-6xl flex-col gap-12 px-8 py-16">
      <header className="space-y-6">
        <span className="badge">Vbescore MVP</span>
        <h1 className="font-display text-5xl font-semibold text-ink">
          Evaluate vibe coding + architecture thinking in one lightweight flow.
        </h1>
        <p className="max-w-2xl text-lg text-slate-600">
          Vbescore lets recruiters create a timed session link. Candidates code in-browser, answer architecture prompts, and submit.
          You get a concise, structured evaluation report generated by an LLM.
        </p>
        <div className="flex flex-wrap gap-3">
          <Link className="rounded-full bg-ink px-5 py-2 text-sm font-semibold text-white" href="/login">
            Sign in
          </Link>
          <Link className="rounded-full border border-slate-200 px-5 py-2 text-sm font-semibold" href="/app">
            Recruiter App
          </Link>
        </div>
      </header>

      <section className="grid gap-6 md:grid-cols-3">
        {[
          {
            title: "Create a session",
            body: "Define the coding prompt + architecture questions in minutes.",
          },
          {
            title: "Share a link",
            body: "Candidates open a public link and complete the assessment.",
          },
          {
            title: "Review the report",
            body: "LLM-generated rubric with strengths, risks, and recommendation.",
          },
        ].map((item) => (
          <div key={item.title} className="card p-6">
            <h3 className="font-display text-xl font-semibold text-ink">{item.title}</h3>
            <p className="mt-2 text-sm text-slate-600">{item.body}</p>
          </div>
        ))}
      </section>
    </main>
  );
}
